# Site settings
title: "@clintcparker"
tagline: Code and such from a whiteboard enthusiast
email: clintcparker@gmail.com
description: > #this is parsed by search engines
   Writings on software development, testing, and architecture.
   .NET C# Tools Testing whiteboarding design
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://clintcparker.com" # the base hostname & protocol for your site
twitter_username: clintcparker
github_username:  clintcparker
social_username: clintcparker
paginate: 5

#Analytics
google_analytics: UA-84920844-2


# Octo settings
#extensions
post_ext: md
page_ext: html

#layouts
post_layout: post
page_layout: page

#titlecase
titlecase: true

#templates
post_template: post
page_template: page
draft_template: draft

# Build settings
markdown: kramdown
highlighter: rouge
sass:
    style: compressed

#plugins
plugins: [jekyll-paginate]

permalink: pretty

exclude:
  - README.md
  - LICENSE
  - Gemfile

# serve options
port: 4000
host: localhost
open_url: true
livereload: true
incremental: false
