# Site settings
title: "@clintcparker"
tagline: Code and such
email: clintcparker@gmail.com
description: > #this is parsed by search engines
   Writings on software development, testing, and architecture.
   .NET C# Tools Testing
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://clintcparker.com" # the base hostname & protocol for your site
twitter_username: clintcparker
github_username:  clintcparker
paginate: 5


# Octo settings
#extensions
post_ext: md
page_ext: html

#layouts
post_layout: post
page_layout: page

#titlecase
titlecase: true

#templates
post_template: post
page_template: page
draft_template: draft

# Build settings
markdown: kramdown
highlighter: rouge
sass:
    style: :compressed

# Gems
gems: [jekyll-paginate]
